### ISSUE TITLE
No module named 'easy_thumbnailshero_slider'

### ISSUE THREAD

**Issue by jTiKey** [bitmazk/django-hero-slider#2]
Any idea, what could be the problem? Django 1.7, python 3.3

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python33\lib\site-packages\django\core\management\__init__.py", line
385, in execute_from_command_line
    utility.execute()
  File "C:\Python33\lib\site-packages\django\core\management\__init__.py", line
354, in execute
    django.setup()
  File "C:\Python33\lib\site-packages\django\__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python33\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python33\lib\site-packages\django\apps\config.py", line 87, in create

    module = import_module(entry)
  File "C:\Python33\lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'easy_thumbnailshero_slider'

**Comment by Tyrdall** [comment]
@jTiKey I bet your INSTALLED_APPS settings looks like this:

     ...
    'easy_thumbnails'
    'hero_slider'
    ...

You will have to add a comma after ``'easy_thumbnails'´´.

**Comment by jTiKey** [comment]
Yup, you are right! In the ReadMe, the comma is missed as well.
