### ISSUE TITLE
NameError: name 'generic' is not defined

### ISSUE THREAD

**Issue by mohamedagamy** [bitmazk/django-hero-slider#4]
### **agamy@agamy:~/Django-Project/blog$ python manage.py runTraceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.2-py2.7.egg/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.2-py2.7.egg/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.2-py2.7.egg/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.2-py2.7.egg/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.9.2-py2.7.egg/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/hero_slider/models.py", line 37, in <module>
    class SliderItem(TranslatableModel):
  File "/usr/local/lib/python2.7/dist-packages/hero_slider/models.py", line 80, in SliderItem
    content_object = generic.GenericForeignKey('content_type', 'object_id')
NameError: name 'generic' is not defined
**

**Comment by Tyrdall** [comment]
@mohamedagamy Fixed in 1.3 :)

**Comment by MahmudJewel** [comment]
In DRF, import generics
`from rest_framework import generics
`
